[package]
name = "state_hierarchy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.0", default-features = false }
either = "1.9.0"
strum = { version = "0.25.0", features = ["derive"] }

[dev-dependencies]
bevy = "0.11.0"
bevy_tweening = "0.8.0"
